
- name: Install certbot
  apt:
    pkg: python-certbot-nginx
    state: latest
    default_release: stretch-backports
  register: certbot_installed
  when: peertube_proxy_handle_https != 'yes'

- name: Install Letsencrypt certificate
  shell: |
    certbot certonly -n \
      --authenticator standalone \
      --installer nginx \
      -d {{ peertube_tld }} \
      -m {{ admin_email }} \
      --agree-tos \
      --pre-hook "systemctl stop nginx" \
      --post-hook "systemctl start nginx"
  when:
    - certbot_installed is changed
    - peertube_proxy_handle_https != 'yes'

- name: Insert Let's encrypt certificates in nginx
  blockinfile:
    dest: /etc/nginx/sites-available/peertube
    marker: "  # {mark} let's encrypt configuration"
    block: |2-
        ssl_certificate /etc/letsencrypt/live/{{ peertube_tld }}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ peertube_tld }}/privkey.pem;
    insertbefore: ".*# Security hardening.*"
    state: present
  when: peertube_proxy_handle_https != 'yes'
  notify:
    - reload nginx
