- name: Install dependencies
  apt: pkg={{item}} state=latest
  with_items:
    - curl
    - sudo
    - unzip
    - vim
    - nginx
    - ffmpeg
    - postgresql
    - openssl
    - g++
    - make
    - redis-server
    - git
    - python-psycopg2
    - build-essential # for bcrypt?
    - apt-transport-https # for node apt repository
    - python-ruamel.yaml

# Configure nodejs
- name: Install NodeJS apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeJS apt repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_9.x "{{ ansible_distribution_release }}" main
    state: present
    filename: nodesource

- name: Install NodeJS
  apt:
    update_cache: yes
    pkg: nodejs
    state: latest

- name: Install Yarn apt key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add Yarn apt repo
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    filename: yarn

- name: Install Yarn
  apt:
    update_cache: yes
    pkg: yarn
    state: latest
